import svelte from 'rollup-plugin-svelte'
import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'

export default [
  {
    input: 'client.js',
    output: {
      dir: 'public',
      format: 'cjs'
    },
    plugins: [
      svelte(),
      resolve({
        browser: true,
        dedupe: ['svelte']
      }),
      commonjs()
    ],
    watch: {
      clearScreen: false
    }
  },
  {
    input: 'Static.svelte',
    output: {
      file: 'static.html'
    },
    plugins: [
      svelte(),
      resolve(),
      {
        generateBundle(options, bundle) {
          const path = require('path')
          const name = path.parse(options.file).base
          const module = bundle[name].facadeModuleId
          // We ignore the bundle[name].code generated by other plugins
          // and load the input module explicitly instead.
          require('svelte/register')
          const Static = require(module).default
          const { html } = Static.render()
          bundle[name].code = html
        }
     }
    ]
  }
]
